### ISSUE TITLE
Select from the list and get question with answers

### ISSUE THREAD

**Issue by PumpkinSeed** [bavaz1/stackoverflow-cli#1]
1. Get the number of the question from the list using the `fmt.Scanf` then read the question's id from the `[]Item`.
2. Send the requests the fetch the question's details and the answers belongs to.
Endpoints: 
- Question: https://api.stackexchange.com/docs/questions-by-ids
- Answers: https://api.stackexchange.com/docs/answers-on-questions

**Comment by bavaz1** [comment]
#b3c9ffc2398a082b1978faa54326e5db375bb28c

**Comment by bavaz1** [comment]
> b3c9ffc2398a082b1978faa54326e5db375bb28c

**Comment by PumpkinSeed** [comment]
Resolved #2
